# dev:
#   adapter:  PostgreSQL
#   database: twitterquiz
#   host:     localhost
#   username: adrian
#   password: adrian
#   port:     5432

dev:
  adapter:  SQLite
  filename: db/tweet-stats.sqlite
