dev:
  adapter:  MySQL
  database: twitterquiz
  host:     localhost
  username: root
  port:     3306
  password: ""

# dev:
#   adapter:  PostgreSQL
#   database: twitterquiz
#   host:     localhost
#   username: adrian
#   port:     5432
#   password: adrian
